#!/bin/sh

set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
  CREATE ROLE  $ROLE  WITH ENCRYPTED PASSWORD '${PASSWORD}';
  CREATE DATABASE $DATABASE  OWNER $ROLE;
  GRANT ALL PRIVILEGES ON DATABASE $DATABASE  TO "$ROLE";
  ALTER ROLE $ROLE LOGIN
EOSQL
